export const ADD_CHARACTER = 'ADD_CHARACTER';
export const EDIT_CHARACTER = 'EDIT_CHARACTER';
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const DELETE_CHARACTER = 'DELETE_CHARACTER';
export const ADD_CURRENT_CHARACTER = 'ADD_CURRENT_CHARACTER';
